######################## default configuration ####################
baseURL = "https:/edcamp.wealgerians.com/"
languageCode = "en"
title = "WE Algerians EdCamp"
theme = "homecamp"
summaryLength = "10"
paginate = 4
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"
IsMultiLingual = true


[languages]
  [languages.ar]
    languagedirection = "rtl"
    LanguageName = "العربية"
    title = "مخيم WE Algerians للتعليم"
    weight = 2
    contentDir = "content/ar"
  [languages.ar.params.i18nplugins]
      [[languages.ar.params.i18nplugins.css]]
        URL = "plugins/bootstrap-rtl/css/bootstrap-rtl.min.css"  
  [languages.ar.params]
      logo = "images/logo-we.png"
      home = "الصفحة الرئيسية"
      description = "WE Algerians EdCamp"
      [languages.ar.params.preloader]
        enable = true
      [languages.ar.params.navBtn]
        enable = false
        label = "تسجيل"
        link = "#"
  [[languages.ar.menu.main]]
      name = "المتحدثون"
      URL = "speaker"
      weight = 3

    [[languages.ar.menu.main]]
      weight = 4
      name = "دروس"
      hasChildren = true

   [[languages.ar.menu.main]]
      parent = "دروس"
      name = "موارد"
      URL = "faq"
    

    [[languages.ar.menu.main]]
        name = "البرنامج"
        URL = "schedule"

  [languages.en]
    LanguageName = "English"
    title = "WE Algerians EdCamp"
    weight = 1
    contentDir = "content/en"
    [languages.en.params]
      logo = "images/logo-we.png"
      home = "Home"
      description = "WE Algerians EdCamp"
      [languages.en.params.preloader]
        enable = true
      [languages.en.params.navBtn]
        enable = false
        label = "Subscribe"
        link = "#"
    [languages.en.params.i18nplugins]
      [[languages.en.params.i18nplugins.css]]
        URL = "plugins/bootstrap/css/bootstrap.min.css"  
    [[languages.en.menu.main]]
      name = "speakers"
      URL = "speaker"
      weight = 3

    [[languages.en.menu.main]]
      weight = 4
      name = "Tutorials"
      hasChildren = true

    [[languages.en.menu.main]]
      parent = "Tutorials"
      name = "Resources"
      URL = "faq"
    

    [[languages.en.menu.main]]
        name = "schedule"
        URL = "schedule"

  


  [languages.fr]
    LanguageName = "Français"
    title = "WE Algerians EdCamp"
    weight = 3
    enable = false
    contentDir = "content/fr"
    [languages.fr.params]
      logo = "images/logo-we.png"
      home = "Accueil"
      description = "WE Algerians EdCamp"
      [languages.fr.params.preloader]
        enable = true
      [languages.fr.params.navBtn]
        enable = false
        label = "Inscription"
        link = "#"
  [languages.fr.params.i18nplugins]
      [[languages.fr.params.i18nplugins.css]]
        URL = "plugins/bootstrap/css/bootstrap.min.css"  
  [[languages.fr.menu.main]]
      name = "Intervenants"
      URL = "speaker"
      weight = 3

    [[languages.fr.menu.main]]
     weight = 4
      name = "Tutoriels"
      hasChildren = true

    [[languages.fr.menu.main]]
      parent = "Tutoriels"
      name = "Ressources"
      URL = "faq"
    

    [[languages.fr.menu.main]]
        name = "Planning"
        URL = "schedule" 


[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/themefisher-font/style.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/SyoTimer/jquery.syotimer.min.js"
  [[params.plugins.js]]
  URL = "http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.32/jquery.form.js"
  [[params.plugins.js]]
  URL = "http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
