######################## default configuration ####################
baseURL = "https:/dz-experts.github.io/homecamp"
languageCode = "en"
title = "WE Algerians EdCamp"
theme = "homecamp"
summaryLength = "10"
paginate = 4
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"
IsMultiLingual = true
[languages]
  [languages.ar]
    languagedirection = "rtl"
    LanguageName = "العربية"
    title = "منتدى تعليمي"
    weight = 2
    contentDir = "content/ar"
  [languages.en]
    LanguageName = "English"
    title = "WE Algerians EdCamp"
    weight = 1
    contentDir = "content/en"
    
  [languages.fr]
    LanguageName = "Français"
    title = "WE Algerians EdCamp"
    weight = 3
    enable = false
    contentDir = "content/fr"

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themefisher-font/style.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/SyoTimer/jquery.syotimer.min.js"
  [[params.plugins.js]]
  URL = "http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.32/jquery.form.js"
  [[params.plugins.js]]
  URL = "http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/map.js"

############################## navigation ###############################
[menu]
      
  [[menu.main]]
  name = "speakers"
  URL = "speaker"
  weight = 3

  [[menu.main]]
  weight = 4
  name = "Tutorials"
  hasChildren = true

  [[menu.main]]
  parent = "Tutorials"
  name = "Resources"
  URL = "faq"
 

    [[menu.main]]
    name = "schedule"
    URL = "schedule"

  
   

#################### default parameters ################################
[params]
logo = "images/logo-we.png"
home = "Home"
# Meta data
description = "WE Algerians EdCamp"


  # Preloader
  [params.preloader]
  enable = true

  # Navigation get start button
  [params.navBtn]
  enable = true
  label = "Subscribe"
  link = "#"

  ############################## footer ################################
  [params.footer]
  title = "WE Algerians EdCamp"
  content = "The objective of this homecamp is twofold: (1) to introduce instructors and students to the world of online education and the flexibility it can offer during this pandemic; and (2) to provide a think tank to brainstorm about the future of the Algerian higher-education institutions and how they can be more competitive."
  copyright = "Copyright Reserved to WE-Algerians. 2020"

  ############################# social icon ############################
 [[params.social]]
 icon = "tf-ion-social-facebook"
 link = "#"
  
[[params.social]]
icon = "tf-ion-social-twitter"
link = "#"
  
[[params.social]]
icon = "tf-ion-social-linkedin"
link = "#"
  